//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidCharts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CovidCharts.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a data set ....
        /// </summary>
        public static string ChooseADataSet {
            get {
                return ResourceManager.GetString("ChooseADataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a province ....
        /// </summary>
        public static string ChooseAProvince {
            get {
                return ResourceManager.GetString("ChooseAProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deceased.
        /// </summary>
        public static string Deceased {
            get {
                return ResourceManager.GetString("Deceased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healed and discharged.
        /// </summary>
        public static string HealedAndDischarged {
            get {
                return ResourceManager.GetString("HealedAndDischarged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitalized with symptoms.
        /// </summary>
        public static string HospitalizedWithSymptoms {
            get {
                return ResourceManager.GetString("HospitalizedWithSymptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In home isolation.
        /// </summary>
        public static string InHomeIsolation {
            get {
                return ResourceManager.GetString("InHomeIsolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensive care.
        /// </summary>
        public static string IntensiveCare {
            get {
                return ResourceManager.GetString("IntensiveCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Nanday.dev.
        /// </summary>
        public static string MainPageSubtitle {
            get {
                return ResourceManager.GetString("MainPageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covid19 Data.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National trend.
        /// </summary>
        public static string NationalTrend {
            get {
                return ResourceManager.GetString("NationalTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New positives.
        /// </summary>
        public static string NewPositives {
            get {
                return ResourceManager.GetString("NewPositives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinces total cases.
        /// </summary>
        public static string ProvincesTotalCases {
            get {
                return ResourceManager.GetString("ProvincesTotalCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show increments only.
        /// </summary>
        public static string ShowIncrementsOnly {
            get {
                return ResourceManager.GetString("ShowIncrementsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cases.
        /// </summary>
        public static string TotalCases {
            get {
                return ResourceManager.GetString("TotalCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total hospitalized.
        /// </summary>
        public static string TotalHospitalized {
            get {
                return ResourceManager.GetString("TotalHospitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total positives.
        /// </summary>
        public static string TotalPositives {
            get {
                return ResourceManager.GetString("TotalPositives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total tested.
        /// </summary>
        public static string TotalTested {
            get {
                return ResourceManager.GetString("TotalTested", resourceCulture);
            }
        }
    }
}
